### ISSUE TITLE
Named types that are slices

### ISSUE THREAD

**Issue by dominikh** [johanbrandhorst/sortslice#1]
sortslice incorrectly flags the following code:

```
type T []int
sort.Slice(T{}, nil)
```

that's because https://github.com/johanbrandhorst/sortslice/blob/23158ff1a9ff103ee7b5401811ca2f5600eb90c8/analyzer.go#L36 is missing a call to (types.Type).Underlying

**Comment by johanbrandhorst** [comment]
Thanks for the bug report!
